d = {
    "Name": "John",
    "Surname": "Smith"
}

print(d["Surname"])

# Explanation: 

# A KeyError in Python occurs when you try to access a key that does not exist